### ISSUE TITLE
RTFaceLogin apk not getting auto-generated (previously "fatal: Authentication failed for 'https://robotutor:@github.com/RoboTutorLLC/RTFace_Login.git/'")

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RTFace_Login#14]
I'm posting this issue because I didn't recognize it in any of these lists:
•	https://github.com/RoboTutorLLC/RoboTutor_2020/issues
•	https://github.com/RoboTutorLLC/RTFace_Login/issues
•	https://github.com/RoboTutorLLC/RoboFeel/issues
If it already exists, please link to it or combine it with this one.

Apparently travis has trouble with python code.
From https://app.travis-ci.com/github/RoboTutorLLC/RTFace_Login end of job log:
...
$ bash scripts/update_apk.sh
RoboTutorLLC/RTFace_Login, 13
Building debug apk
...
create mode 100644 RTFace_Login-travis-apk-2021-08-26.apk
remote: Invalid username or password.
**fatal: Authentication failed for 'https://robotutor:@github.com/RoboTutorLLC/RTFace_Login.git/'**
Done. Your build exited with 0.

**Comment by JackMostow** [comment]
@sushant-varanasi - Is this issue fixed and should therefore be closed?

**Comment by sushant-varanasi** [comment]
This issue isn't fixed yet. We had tried various experiments and trials to solve it back then but had the same error every time in the last step of Travis apk generation.

**Comment by JackMostow** [comment]
@sushant-varanasi Dang!  I'd forgotten.  Googling "travis python authentication error" shows that many others hit the same issue.
Unless you have a quick solution in mind, I hate for you to spend yet more time on this problem.
What's Plan B for generating new apks for RTFaceLogin?  E.g. can you post a README for how to do it manually?

**Comment by sansyrox** [comment]
@sushant-varanasi , did you try generating a new GitHub access token?

**Comment by sansyrox** [comment]
Also, from the logs(https://api.travis-ci.com/v3/job/557636826/log.txt), you can see that the cloning works well. It is highly likely that authentication is fine.

It is either build version issues or maybe you can try investigating the keystone. As the build is failing.



```
Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0.2/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/travis/build/RoboTutorLLC/RTFace_Login/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
travis_time:end:274b1e5a:start=1643594701127154188,finish=1643594742072151604,duration=40944997416,event=after_success
[0Ktravis_fold:end:after_success
[0K
Done. Your build exited with 0.
```

**Comment by JackMostow** [comment]
@sushant-varanasi - @sansyrox recommends:


In the robotutor 2020 repo look at the `env` key

```
language: android
dist: trusty
sudo: false
jdk:
............
script:
- cp -v app/src/sample_config_files/sample_keystore.properties keystore.properties
- keytool -genkeypair -dname "cn=TravisCI, ou=TravisCI, o=Sun, c=US" -alias business
  -keypass kpi135 -keystore android.keystore -storepass ab987c -validity 20000
after_success:
- bash scripts/update_apk.sh
branches:
  only:
  - master
  - development
env:
  global:
    secure: some secret key

```


Whereas RTFaceLogin's travis.yml doesn't have it.

```
language: android
dist: trusty
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - android-26

    - build-tools-29.0.2
    - platform-tools
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "${TRAVIS_BUILD_DIR}/gradle/caches/"
    - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
script:
  - cp -v sample_config_files/sample_keystore.properties keystore.properties
  - keytool -genkeypair -dname "cn=TravisCI, ou=TravisCI, o=Sun, c=US" -alias business
    -keypass kpi135 -keystore android.keystore -storepass ab987c -validity 20000
after_success:
  - bash scripts/update_apk.sh
branches:
  only:
    - master
    - development

```


You need to generate a new travis secret and add it to that file.

>  The encrypted variable is the gh token being used here(https://github.com/RoboTutorLLC/RoboTutor_2020/blob/8f641dd046be66fbf45d186a51fcd2d1307e5014/scripts/update_apk.sh#L38) . You would have to ask for it again from Dr Mostow and encrypt it again while adding it.(read more here https://docs.travis-ci.com/user/environment-variables/#:~:text=credentials%20to%20your%20.-,travis.,requests%20coming%20from%20another%20repository.&text=Encrypted%20environment%20variables%20are%20not,such%20information%20to%20unknown%20code.)
